import { useEffect, useState } from 'react';
import { EmptyState, ErrorNotice, LoadingState, Metric, PageHeader, Panel, StatusBadge } from '../components/ui';
import { useI18n } from '../i18n/I18nContext';
import { formatScore } from '../utils/format';

export function AgentsPage({ api }) {
  const { t } = useI18n(); const [state, setState] = useState({ loading: true, agents: [], performance: [], error: null });
  useEffect(() => { let active = true; (async () => { try { const response = await api.getAgents(); const agents = response.agents || []; const performance = await Promise.all(agents.map(async (agent) => { try { return await api.getAgentPerformance(agent.id); } catch { return null; } })); if (active) setState({ loading: false, agents, performance, error: null }); } catch (error) { if (active) setState({ loading: false, agents: [], performance: [], error }); } })(); return () => { active = false; }; }, [api]);
  return <><PageHeader eyebrow="SYSTEM" title={t('agents.title')} description={t('agents.subtitle')} />{state.loading ? <LoadingState /> : <><ErrorNotice error={state.error} />{state.agents.length ? <div className="agent-page-grid">{state.agents.map((agent, index) => { const stats = state.performance[index]?.global; return <Panel key={agent.id} className="agent-detail-card"><div className="agent-card-heading"><div><h2>{agent.name}</h2><code>{agent.id}</code></div><StatusBadge value={agent.available ? 'available' : 'unavailable'} /></div><div className="metric-grid metric-grid-compact"><Metric label={t('agents.host')} value={<StatusBadge value={agent.host?.installed || agent.installed ? 'available' : 'unavailable'} />} detail={agent.host?.version || agent.version} /><Metric label={t('agents.runtime')} value={agent.runtime || t('common.notAvailable')} /><Metric label={t('agents.sandbox')} value={agent.sandbox?.available ? agent.sandbox.backend || 'ready' : t('common.notAvailable')} /><Metric label={t('agents.performance')} value={stats?.sampleSize ? formatScore(stats.averageEvaluationScore) : t('performance.noHistory')} detail={stats?.sampleSize ? `${stats.sampleSize} ${t('common.samples')}` : null} /></div></Panel>; })}</div> : <EmptyState>{t('candidate.noCandidates')}</EmptyState>}</>}</>;
}
