import { fireEvent, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import { CandidatePage } from './CandidatePage';
import { render } from '../test/render';

const fingerprint = `sha256:${'b'.repeat(64)}`;
function review(overrides = {}) { return { task: { id: 'task-1', task: 'Update README', mode: 'single', status: 'completed', targetBranch: 'main', baseCommit: 'abc123', decision: 'pending' }, candidate: { agentId: 'qwen-code', status: 'completed', evaluationScore: 98, verdict: 'pass', competitionScore: null, branch: 'agent/task-1-qwen-code', worktree: 'C:\\repo\\.agent-worktrees\\task-1-qwen-code', changedFiles: ['README.md'], untrackedFiles: ['notes.txt'], trackedDiff: '+<script>alert("x")</script>', diffRedacted: false, fingerprint }, approvable: true, reason: null, ...overrides }; }
function apiFor(candidateReview = review()) { return { getCandidate: vi.fn().mockResolvedValue(candidateReview), approveCandidate: vi.fn().mockResolvedValue({ status: 'merged', candidateCommit: 'commit-1', mergeCommit: 'merge-1', cleanupWarnings: [] }), rejectCandidate: vi.fn().mockResolvedValue({ status: 'rejected', cleanupWarnings: [] }) }; }
async function load(api) { window.history.replaceState({}, '', '/candidates?taskId=task-1'); render(<CandidatePage api={api} />); await userEvent.click(screen.getByRole('button', { name: 'Load Candidate' })); await screen.findByText('REVIEW'); }

describe('Candidate Review page', () => {
  it('confirms and passes the exact reviewed fingerprint without duplicate approval', async () => { const api = apiFor(); await load(api); await userEvent.click(screen.getByRole('button', { name: 'Approve' })); const dialog = screen.getByRole('dialog', { name: 'Approve Candidate?' }); expect(dialog).toHaveTextContent('Remote push will NOT be performed'); const approve = within(dialog).getByRole('button', { name: 'Approve' }); await userEvent.dblClick(approve); expect(api.approveCandidate).toHaveBeenCalledTimes(1); expect(api.approveCandidate).toHaveBeenCalledWith('task-1', fingerprint); expect(await screen.findByText('merge-1')).toBeInTheDocument(); });
  it('requires confirmation before rejection and reports target untouched', async () => { const api = apiFor(); await load(api); await userEvent.click(screen.getByRole('button', { name: 'Reject' })); expect(api.rejectCandidate).not.toHaveBeenCalled(); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Reject' })); expect(api.rejectCandidate).toHaveBeenCalledWith('task-1'); expect(await screen.findByText('Target repository was not modified.')).toBeInTheDocument(); });
  it.each([['candidate_changed', /candidate files changed/u], ['stale_base', /target branch advanced/u]])('shows %s conflict and requires review again', async (code, copy) => { const api = apiFor(); api.approveCandidate.mockRejectedValue(Object.assign(new Error(code), { status: 409, code })); await load(api); await userEvent.click(screen.getByRole('button', { name: 'Approve' })); await userEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Approve' })); expect(await screen.findByText(copy)).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Refresh Candidate for review' })).toBeInTheDocument(); expect(api.approveCandidate).toHaveBeenCalledTimes(1); expect(screen.queryByText(/^Approved$/)).toBeNull(); });
  it('disables approval for backend-declared unsafe candidates', async () => { const api = apiFor(review({ approvable: false, reason: 'candidate_unsafe' })); await load(api); expect(screen.getByRole('button', { name: 'Approve' })).toBeDisabled(); expect(screen.getByText('candidate_unsafe')).toBeInTheDocument(); });
  it('requires typed APPROVE for warning candidates', async () => { const api = apiFor(review({ candidate: { ...review().candidate, verdict: 'warning' } })); await load(api); await userEvent.click(screen.getByRole('button', { name: 'Approve' })); const dialog = screen.getByRole('dialog', { name: 'High-risk approval' }); expect(within(dialog).getByRole('button', { name: 'Approve' })).toBeDisabled(); const input = within(dialog).getByLabelText('Type APPROVE'); fireEvent.change(input, { target: { value: 'APPROVE' } }); expect(input).toHaveValue('APPROVE'); await waitFor(() => expect(within(dialog).getByRole('button', { name: 'Approve' })).toBeEnabled()); });
  it('renders already approved as a known state', async () => { const api = apiFor(review({ task: { ...review().task, decision: 'approved' } })); await load(api); expect(screen.queryByRole('button', { name: 'Approve' })).toBeNull(); expect(screen.getByText(/approved/i)).toBeInTheDocument(); });
});
