import { useEffect, useState } from 'react';
import { EmptyState, ErrorNotice, LoadingState, Metric, PageHeader, Panel, StatusBadge } from '../components/ui';
import { useI18n } from '../i18n/I18nContext';
import { CATEGORIES, formatDuration, formatPercent, formatScore } from '../utils/format';

function Stats({ stats, category = false }) {
  const { t } = useI18n();
  if (!stats || stats.sampleSize === 0) return <EmptyState>{t('performance.noHistory')}</EmptyState>;
  return <div className="metric-grid metric-grid-compact"><Metric label={t('common.samples')} value={stats.sampleSize} /><Metric label={category ? t('performance.weighted') : t('performance.average')} value={formatScore(category ? stats.weightedEvaluationScore : stats.averageEvaluationScore)} /><Metric label={t('performance.passRate')} value={formatPercent(stats.passRate)} />{!category && <><Metric label={t('performance.success')} value={formatPercent(stats.successRate)} /><Metric label={t('performance.warningRate')} value={formatPercent(stats.warningRate)} /><Metric label={t('performance.failureRate')} value={formatPercent(stats.failureRate)} /></>}<Metric label={t('run.duration')} value={formatDuration(stats.averageDurationMs)} /></div>;
}

export function PerformancePage({ api }) {
  const { t } = useI18n(); const [agents, setAgents] = useState([]); const [agentId, setAgentId] = useState(''); const [category, setCategory] = useState('coding'); const [performance, setPerformance] = useState(null); const [categoryStats, setCategoryStats] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  useEffect(() => { let active = true; api.getAgents().then((response) => { if (!active) return; const next = response.agents || []; setAgents(next); setAgentId((current) => current || next[0]?.id || ''); }).catch((requestError) => { if (active) setError(requestError); }); return () => { active = false; }; }, [api]);
  useEffect(() => { if (!agentId) { setLoading(false); return undefined; } let active = true; setLoading(true); setError(null); Promise.all([api.getAgentPerformance(agentId), api.getCategoryPerformance(agentId, category)]).then(([overall, response]) => { if (active) { setPerformance(overall); setCategoryStats(response.performance); } }).catch((requestError) => { if (active) setError(requestError); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [agentId, api, category]);
  return <><PageHeader eyebrow="ADAPTIVE ROUTING EVIDENCE" title={t('performance.title')} description={t('performance.subtitle')} /><Panel><div className="filter-row"><label htmlFor="performance-agent">Agent</label><select id="performance-agent" value={agentId} onChange={(event) => setAgentId(event.target.value)}>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.name} {!agent.available ? `(${t('status.unavailable')})` : ''}</option>)}</select><label htmlFor="performance-category">{t('performance.category')}</label><select id="performance-category" value={category} onChange={(event) => setCategory(event.target.value)}>{CATEGORIES.map((name) => <option key={name} value={name}>{t(`category.${name}`)}</option>)}</select></div></Panel><ErrorNotice error={error} />{loading ? <LoadingState /> : !performance ? <EmptyState>{t('performance.noHistory')}</EmptyState> : <div className="result-stack"><Panel><div className="agent-title"><div><h2>{performance.agent.name || performance.agent.id}</h2><small>{performance.agent.id}</small></div><StatusBadge value={performance.agent.available ? 'available' : 'unavailable'} /></div></Panel><Panel title={t('performance.global')}><Stats stats={performance.global} /></Panel><Panel title={t('performance.recent')}><Stats stats={performance.recent} /></Panel><Panel title={`${t('performance.category')} · ${t(`category.${category}`)}`}><Stats stats={categoryStats} category /></Panel></div>}</>;
}
